qblade_to_openfast_map = {
    'Time': 'Time',
    'Rotational Speed': 'RotSpeed',
    'LSS Azimuthal Pos.': 'Azimuth',
    'Gen. HSS Torque': 'GenTq',
    'Gen. Elec. Power': 'GenPwr',
    'HSS Rpm': 'GenSpeed',
    'Pitch Angle BLD_1': 'BldPitch1',
    'Pitch Vel. BLD_1' : 'BlPitchV1',
    'Yaw Angle': 'NacYaw',
    r"X_b\s+Tip\s+Trl\.Def\.\s+\(FLAP\)\s+BLD_1" : 'TipDxb1',
    r"X_c\s+Tip\s+Trl\.Def\.\s+\(OOP\)\s+BLD_1": 'TipDxc1',
    'Y_tb Mom. TWR Bot. Constr.': 'TwrBsMyt',
    'NP Trans. X_g': 'PtfmSurge',
    'NP Trans. Y_g': 'PtfmSway',
    'NP Trans. Z_g': 'PtfmHeave',
    'NP Roll X_l': 'PtfmRoll',
    'NP Pitch Y_l': 'PtfmPitch',
    'NP Yaw Z_l': 'PtfmYaw',
    'Abs Inflow Vel. at Hub': 'Wind1Vel',
    'X_g Inflow Vel. at Hub': 'Wind1VelX', 
    'Y_g Inflow Vel. at Hub': 'Wind1VelY', 
    'Z_g Inflow Vel. at Hub': 'Wind1VelZ', 
    'Wave Elev. HYDRO WavekinEval. Pos.': "Wave1Elev", 
    'NP Wave Elevation': 'Wave1Elev',
    'X_b RootBend. Mom. BLD_1': 'RootMxb1',
    'Y_b RootBend. Mom. BLD_1': 'RootMyb1',
    #'Z_b Rot.Def. BLD_1 pos 1.000': 'TipRzc1',
    'Aero. Power Coefficient': 'RtAeroCp',
    'Aero. Power': 'RtAeroPwr',
    'Aero. LSS Torque': 'RtAeroTq',
    'Thrust Coefficient': 'RtAeroCt',
    r"Angle of Attack BLD_1 pos (\d+\.\d+)": r"B1Alpha_\1",
    r"Angle of Attack BLD_2 pos (\d+\.\d+)": r"B2Alpha_\1",
    r"Angle of Attack BLD_3 pos (\d+\.\d+)": r"B3Alpha_\1",
    r"Y_c Mom. BLD_1 pos": "",
    r"X_h For. Hub Const.": 'LSShftFxh',
    r"X_s For. Shaft Const.": 'LSShftFxa',
    r"Y_s For. Shaft Const.": 'LSShftFys', 
    r"Z_s For. Shaft Const.": 'LSShftFzs',    
    r"X_s Mom. Shaft Const.": 'LSShftMxs', 
    r"Y_s Mom. Shaft Const.": 'LSShftMys', 
    r"Z_s Mom. Shaft Const.": 'LSShftMzs',
    r'X_c Root For. BLD_1': 'RootFxc1',
    r'Y_c Root For. BLD_1': 'RootFyc1',
    r'Z_c Root For. BLD_1': 'RootFzc1',   
    r"X_c\s+RootBend\.\s+Mom\.\s+\(IP\)\s+BLD_1": 'RootMxc1',
    r"Y_c\s+RootBend\.\s+Mom\.\s+\(OOP\)\s+BLD_1": 'RootMyc1',
    r"Z_c RootBend. Mom. BLD_1": 'RootMzc1',
    r'X_n Nac. Acc.': 'NcIMUTAxn',
    r'Y_n Nac. Acc.': 'NcIMUTAyn',
    r'Z_n Nac. Acc.': 'NcIMUTAzn',
    r'X_b For. BLD_1 pos (\d+\.\d+)':  r'Fxb1_\1',
    r'Y_b For. BLD_1 pos (\d+\.\d+)':  r'Fyb1_\1',
    r'Z_b For. BLD_1 pos (\d+\.\d+)':  r'Fzb1_\1',
    r'X_b Mom. BLD_1 pos (\d+\.\d+)':  r'Mxb1_\1',
    r'Y_b Mom. BLD_1 pos (\d+\.\d+)':  r'Myb1_\1',
    r'Z_b Mom. BLD_1 pos (\d+\.\d+)':  r'Mzb1_\1',
    r'X_b Trl.Def. BLD_1 pos (\d+\.\d+)':  r'TDxb1_\1',
    r'Y_b Trl.Def. BLD_1 pos (\d+\.\d+)':  r'TDyb1_\1',
    r'Z_b Trl.Def. BLD_1 pos (\d+\.\d+)':  r'TDzb1_\1',
    r'X_b Rot.Def. BLD_1 pos (\d+\.\d+)':  r'RDxb1_\1',
    r'Y_b Rot.Def. BLD_1 pos (\d+\.\d+)':  r'RDyb1_\1',
    r'Z_b Rot.Def. BLD_1 pos (\d+\.\d+)':  r'RDzb1_\1',
    r'X_c For. BLD_1 pos (\d+\.\d+)':  r'Fxc1_\1',
    r'Y_c For. BLD_1 pos (\d+\.\d+)':  r'Fyc1_\1',
    r'X_c Mom. BLD_1 pos (\d+\.\d+)':  r'Mxc1_\1',
    r'Y_c Mom. BLD_1 pos (\d+\.\d+)':  r'Myc1_\1',
    r'Z_l For. BLD_1 pos (\d+\.\d+)': r'Fzl1_\1',
    r'X_l Mom. BLD_1 pos (\d+\.\d+)': r'Mxl1_\1',
    r'Y_l Mom. BLD_1 pos (\d+\.\d+)': r'Myl1_\1',
    r'Z_l For. BLD_2 pos (\d+\.\d+)':  r'Fzl1_\1',
    r'X_l Mom. BLD_2 pos (\d+\.\d+)':  r'Mxl1_\1',
    r'Y_l Mom. BLD_2 pos (\d+\.\d+)':  r'Myl1_\1',  
    r'X_c Trl.Def. BLD_1 pos (\d+\.\d+)': r'TDxc1_\1',
    r'Y_c Trl.Def. BLD_1 pos (\d+\.\d+)': r'TDyc1_\1',
    r'Z_c Trl.Def. BLD_1 pos (\d+\.\d+)':  r'TDzc1_\1',
    r'X_c Rot.Def. BLD_1 pos (\d+\.\d+)':  r'RDxc1_\1',
    r'Y_c Rot.Def. BLD_1 pos (\d+\.\d+)':  r'RDyc1_\1',
    r'Z_c Rot.Def. BLD_1 pos (\d+\.\d+)':  r'RDzc1_\1',
    r'X_tb For. TWR Bot. Constr.':  'TwrBsFxt',
    r'Y_tb For. TWR Bot. Constr.':  'TwrBsFyt',
    r'Z_tb For. TWR Bot. Constr.':  'TwrBsFzt',
    r'X_tb Mom. TWR Bot. Constr.':  'TwrBsMxt', 
    r'Y_tb Mom. TWR Bot. Constr.':  'TwrBsMyt', 
    r'Z_tb Mom. TWR Bot. Constr.':  'TwrBsMzt',
    r'X_c Tip Trl.Def. (OOP) BLD_1':  'TipDxc1', 
    r"Y_c\s+Tip\s+Trl\.Def\.\s+\(IP\)\s+BLD_1":  'TipDyc1', 
    r'Z_c Tip Trl.Def. BLD_1':  'TipDzc1',
    r'X_c Tip Trl.Def. (OOP) BLD_2':  'TipDxc2', 
    r'Y_c Tip Trl.Def. (IP) BLD_2':  'TipDyc2', 
    r'Z_c Tip Trl.Def. BLD_2':  'TipDzc2',
    r'X_c Tip Trl.Def. (OOP) BLD_3':  'TipDxc3', 
    r'Y_c Tip Trl.Def. (IP) BLD_3':  'TipDyc3', 
    r'Z_c Tip Trl.Def. BLD_3':  'TipDzc3',
    'X_c Aero. Force BLD_1 pos (\d+\.\d+)':  r'AeroFxb1_\1',
    'Y_c Aero. Force BLD_1 pos (\d+\.\d+)':  r'AeroFyb1_\1',
    'Aerodynamic Thrust': r'RtAeroTh',
  
}